### ISSUE TITLE
auto deploy

### ISSUE THREAD

**Issue by nihgwu** [nihgwu/hexo-hey#11]

**Comment by pozitron57** [comment]
Is it supposed to work like this:
- `hexo server` at the server where my site is hosted **or** locally 
- browse `mysite.com/admin/` **or** `localhost:4000/admin/`
- create/edit/delete post
- hit `Deploy` button (which I think you are going to add) and the static files will be copied to the desired place (via `rsync`, for example)

?

**Comment by nihgwu** [comment]
right, i'm planning to support that feature, thanks for you comment :smile:

**Comment by pozitron57** [comment]
OK, so I say :+1: for this feature!
