### ISSUE TITLE
本地修改密码和用户名无法登录

### ISSUE THREAD

**Issue by chonghua** [nihgwu/hexo-hey#12]
修改config文件，自定用户名和密码，然后无法登录，提示用户名或者密码错误，使用默认和自定义的均提示错误。

**Comment by nihgwu** [comment]
无法重现，我测试修改了根目录的配置文件`_config.yml`，没有出现你所描述的问题

**Comment by chaozh** [comment]
确实有时存在这种情况，原因不明

**Comment by nihgwu** [comment]
@chaozh 是有时还是一直 请问你们是在mac还是win下修改的配置文件，我怀疑根编辑器和文件保存格式有关，还有密码修改有没有特殊字符之类的？我只测试了把 hexo+hey改成neo+neo并改回来都没问题 @chonghua

**Comment by chonghua** [comment]
Win,但是改回默认密码却可以

**Comment by nihgwu** [comment]
@chonghua 是最新版吗？
最近太忙一直没时间更新，过段时间要好好改改 :smile:

**Comment by chonghua** [comment]
是最新版，没有特殊字符。

发送自我的 BlackBerry 10 智能手机。
发件人： Neo
已发送： 2015年11月19日星期四 13:04
收件人： nihgwu/hexo-hey
答复： nihgwu/hexo-hey
抄送： chonghua
主题： Re: [hexo-hey] 本地修改密码和用户名无法登录 (#12)

@chonghua 是最新版吗？
最近太忙一直没时间更新，过段时间要好好改改 :smile:

---

**Comment by nihgwu** [comment]
我在win 10下用最新的v0.4.1测试没这个问题
