### ISSUE TITLE
Site address

### ISSUE THREAD

**Issue by pozitron57** [nihgwu/hexo-hey#16]
Hey,

If I run `hexo serve` on my server, I can access  `mysite.com/admin` and `mysite.com:4000` will be automatically updated accordingly with changes I do in admin. What is the way to make it appear at `mysite.com` instead of `mysite.com:4000`?

**Comment by nihgwu** [comment]
edit your nginx conf to serve you static folder or you can use other static site server

**Comment by pozitron57** [comment]
Ok, thanks! I thought about it but had doubts.

**Comment by pozitron57** [comment]
@nihgwu, I am sorry, but I reread your comment and it came out that I didn't get it very well.
1. Did you mean `public` directory by "static folder"? If so, `public` will not be created with `hexo server` command. So I manually will have to do `hexo generate`. Which is not what I am looking for. The main attraction for me of `hexo-hey` plugin is that I can create/edit posts using web-interface from my mobile phone! 
2. What did you mean by 
   
   > you can use other static site server
   
   ?

**Comment by nihgwu** [comment]
the `hexo server` command will exec `hexo generate` for you, so if you edit your source files, the `public` folder will update to the new version, or for similarity you can just use the `nginx` to serve your local 3000 port to outer 80 port
i said `use other static site server` in case you don't use `nginx` to serve your site

**Comment by pozitron57** [comment]
Thanks for your answer.
OK, it's clear about `nginx` now, thanks. 

I didn't know that `hexo server` execs `hexo generate`. So when you browse `localhost:4000` you actually browse public directory with static files?

**Comment by nihgwu** [comment]
that's right, `hexo server` is a static site server and besides watch the changes of your source fold and then generate them

**Comment by pozitron57** [comment]
Thanks a lot.
