### ISSUE TITLE
Sidebar on the left is buggy, hexo hey customization fonts suggestion

### ISSUE THREAD

**Issue by nekomeowww** [nihgwu/hexo-hey#27]
## Sidebar Bug

Whether in Windows (10 · Chrome)or Mac OS (El Captain · Chrome), after I click the posts on the sidebar, the sidebar become so strange on the web page.
Here is the screenshot on the demo.

![](http://i13.tietuku.com/66d1f099ac6654bf.jpg)
## Customization Font

As for another thing, I suggest to develope a optional configuration which is users could customize their favorite font for hexo hey. When I engaged in Chinese language, I found out the default font is not as good as for the UI design, I hope I can config it as my own.

---

Sorry about my English.

**Comment by nihgwu** [comment]
I've test the ui in Windows and Mac OS both, and i can't reproduce it now, if so, it would be an issue for angular-materiel.
For the second, the config section only custom the back-end behave so i can't do that, but i will change the `font-family` in the front-end directly :smile:

**Comment by nekomeowww** [comment]
Is there any possibility that I can fix the Angular Material issue?
As for fonts, where can I find the <code>font-family</code>?
