### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by johntom** [nihgwu/hexo-hey#34]
I cant login to try demo
http://nihgwu.github.io/hexo-hey/
username: hexo
passowrd: hey
Thanks,
John

**Comment by nihgwu** [comment]
sorry my VPS is down, you can try it in local

**Comment by johntom** [comment]
Just posted fix see https://github.com/nihgwu/hexo-hey/issues/33
Happy New Year

**Comment by nihgwu** [comment]
Happy new year

? 2017?1?1??01:48?John Tomaselli <notifications@github.com<mailto:notifications@github.com>> ???


Just posted fix see #33<https://github.com/nihgwu/hexo-hey/issues/33>
Happy New Year

-
