### ISSUE TITLE
Unable to log in the admin page

### ISSUE THREAD

**Issue by chaozh** [nihgwu/hexo-hey#7]
Unable to log in the admin page due to the cross site ajax request.
XMLHttpRequest cannot load http://hey.liteneo.com/api/login. The 'Access-Control-Allow-Origin' header has a value 'http://nihgwu.github.io' that is not equal to the supplied origin. Origin 'http://localhost:4000' is therefore not allowed access.

**Comment by nihgwu** [comment]
- **secret** is a key to encrypt you token for login status
- **expire** defined when your login status with be expired in minutes
- **cors** is useful when you want serve your hey in another host with a diffirent hostname

take this demo for example, the hexo blog is hosted on [DO](http://hey.liteneo.com) white the hexo hey is hosted on [Github](http://nihgwu.github.io/hexo-hey), then you need to add http://nihgwu.github.io to your **CORS** whitelist to  access the `api` provided by http://hey.liteneo.com/api
so for the most situations the **cors** config is not nesserary

**Comment by nihgwu** [comment]
@chaozh surprised to find we are schoolmates :astonished:

**Comment by nihgwu** [comment]
sorry, i found that i add a custom apiurl for test but built in the release version, working on it

**Comment by nihgwu** [comment]
please update to v0.3.1

**Comment by chaozh** [comment]
Great! I'll have a try.

**Comment by nihgwu** [comment]
thanks for your feedback
